[package]
name = "temp_convertor"
version = "0.1.0"
authors = ["Vivek_Singh <viveks@akamai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
